[tox]
minversion = 4.6.3
env_list = pytest, mypy, pylint, black, isort

[testenv:pytest]
description = run tests
extras = driven, graph
deps = pytest
commands = pytest {posargs:tests}

[testenv:mypy]
description = run type checks
extras = driven, graph
deps =
    mypy
    pytest
commands = mypy {posargs:src tests}

[testenv:pylint]
description = run linters
deps = pylint
commands = pylint {posargs:src}

[testenv:black]
description = run code formatters
skip_install = true
deps = black[jupyter]
commands = black {posargs:.}

[testenv:isort]
description = run import formatters
skip_install = true
deps = isort
commands = isort {posargs:.}
